# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: gacha.proto for package 'gacha'

require 'grpc'
require 'gacha_pb'

module Gacha
  module Gacha
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gacha.Gacha'

      rpc :Lottery, Request, Response
    end

    Stub = Service.rpc_stub_class
  end
end
