# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gacha.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gacha.Card" do
    optional :name, :string, 1
  end
  add_message "gacha.Request" do
    repeated :cards, :message, 1, "gacha.Card"
  end
  add_message "gacha.Response" do
    optional :card, :message, 1, "gacha.Card"
    optional :ret_code, :int32, 2
  end
end

module Gacha
  Card = Google::Protobuf::DescriptorPool.generated_pool.lookup("gacha.Card").msgclass
  Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("gacha.Request").msgclass
  Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("gacha.Response").msgclass
end
